on:
  push:
    branches:
      - main
      - '*'

jobs:
  build_and_push_to_ecr:
    name: Build Docker image and Push to ECR if Branch is main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ $GITHUB_REF == 'refs/heads/main' ]; then
            aws ecr get-login-password --region eu-west-1 --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
            rev=$(git rev-parse --short HEAD)
            docker build . -t ${{github.sha.short}}
            docker tag ${{github.sha.short}} kan-2041/${{github.sha.short}}
            docker tag ${{github.sha.short}} 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kan-2041-ecr:$rev
            docker push kan-2041/${{github.sha.short}}
            docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kan-2041-ecr:$rev
          else
            rev=$(git rev-parse --short HEAD)
            docker build . -t ${{github.sha.short}}
            docker tag ${{github.sha.short}} kan-2041/${{github.sha.short}}
            docker tag ${{github.sha.short}} 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kan-2041-ecr:$rev
          fi